export const data = {
    "sinceId": 0,
    "maxId": 1149518237870071808,
    "refreshUrl": "?since_id=1149518237870071808&q=obama&include_entities=1",
    "count": 10,
    "completedIn": 0.075,
    "query": "obama",
    "tweets": [
      {
        "createdAt": 1562901479000,
        "id": 1149518237870071808,
        "idStr": "1149518237870071808",
        "text": "RT @realDonaldTrump: Democrats had to quickly take down a tweet called “Kids In Cages, Inhumane Treatment at the Border,” because the horri…",
        "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "inReplyToScreenName": null,
        "geoLocation": null,
        "place": null,
        "retweetCount": 25909,
        "retweetedStatus": {
          "createdAt": 1562846926000,
          "id": 1149289425836367872,
          "idStr": "1149289425836367872",
          "text": "Democrats had to quickly take down a tweet called “Kids In Cages, Inhumane Treatment at the Border,” because the ho… https://t.co/xdiz18B25i",
          "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
          "inReplyToStatusId": -1,
          "inReplyToUserId": -1,
          "inReplyToScreenName": null,
          "geoLocation": null,
          "place": null,
          "retweetCount": 25909,
          "retweetedStatus": null,
          "userMentionEntities": [
            
          ],
          "hashtagEntities": [
            
          ],
          "mediaEntities": [
            
          ],
          "currentUserRetweetId": -1,
          "user": {
            "id": 25073877,
            "idStr": "25073877",
            "name": "Donald J. Trump",
            "screenName": "realDonaldTrump",
            "location": "Washington, DC",
            "description": "45th President of the United States of America🇺🇸",
            "descriptionURLEntities": [
              
            ],
            "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/874276197357596672/kUuht00m_normal.jpg",
            "url": "https://t.co/OMxB0x7xC5",
            "followersCount": 61853221,
            "status": null,
            "profileBackgroundColor": "6D5C18",
            "profileTextColor": "333333",
            "profileLinkColor": "1B95E0",
            "profileSidebarFillColor": "C5CEC0",
            "profileSidebarBorderColor": "BDDCAD",
            "profileUseBackgroundImage": true,
            "showAllInlineMedia": false,
            "friendsCount": 47,
            "createdAt": 1237383998000,
            "favouritesCount": 7,
            "utcOffset": -1,
            "timeZone": null,
            "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
            "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
            "profileBackgroundTiled": true,
            "lang": null,
            "statusesCount": 42819,
            "translator": false,
            "listedCount": 105155,
            "geoEnabled": true,
            "contributorsEnabled": false,
            "originalProfileImageURLHttps": "https://pbs.twimg.com/profile_images/874276197357596672/kUuht00m.jpg",
            "profileImageURL": "http://pbs.twimg.com/profile_images/874276197357596672/kUuht00m_normal.jpg",
            "biggerProfileImageURL": "http://pbs.twimg.com/profile_images/874276197357596672/kUuht00m_bigger.jpg",
            "miniProfileImageURL": "http://pbs.twimg.com/profile_images/874276197357596672/kUuht00m_mini.jpg",
            "originalProfileImageURL": "http://pbs.twimg.com/profile_images/874276197357596672/kUuht00m.jpg",
            "profileImageURLHttps": "https://pbs.twimg.com/profile_images/874276197357596672/kUuht00m_normal.jpg",
            "biggerProfileImageURLHttps": "https://pbs.twimg.com/profile_images/874276197357596672/kUuht00m_bigger.jpg",
            "miniProfileImageURLHttps": "https://pbs.twimg.com/profile_images/874276197357596672/kUuht00m_mini.jpg",
            "profileBackgroundImageURL": "http://abs.twimg.com/images/themes/theme1/bg.png",
            "profileBannerURL": "https://pbs.twimg.com/profile_banners/25073877/1560920145/web",
            "profileBannerRetinaURL": "https://pbs.twimg.com/profile_banners/25073877/1560920145/web_retina",
            "profileBannerIPadURL": "https://pbs.twimg.com/profile_banners/25073877/1560920145/ipad",
            "profileBannerIPadRetinaURL": "https://pbs.twimg.com/profile_banners/25073877/1560920145/ipad_retina",
            "profileBannerMobileURL": "https://pbs.twimg.com/profile_banners/25073877/1560920145/mobile",
            "profileBannerMobileRetinaURL": "https://pbs.twimg.com/profile_banners/25073877/1560920145/ipad_retina",
            "verified": true,
            "followRequestSent": false,
            "urlentity": {
              "start": 0,
              "end": 23,
              "url": "https://t.co/OMxB0x7xC5",
              "expandedURL": "http://www.Instagram.com/realDonaldTrump",
              "displayURL": "Instagram.com/realDonaldTrump"
            },
            "protected": false,
            "rateLimitStatus": null,
            "accessLevel": 0
          },
          "contributors": [
            
          ],
          "urlentities": [
            {
              "start": 117,
              "end": 140,
              "url": "https://t.co/xdiz18B25i",
              "expandedURL": "https://twitter.com/i/web/status/1149289425836367872",
              "displayURL": "twitter.com/i/web/status/1…"
            }
          ],
          "favorited": false,
          "retweet": false,
          "retweetedByMe": false,
          "possiblySensitive": false,
          "truncated": true,
          "rateLimitStatus": null,
          "accessLevel": 0
        },
        "userMentionEntities": [
          {
            "start": 3,
            "end": 19,
            "name": "Donald J. Trump",
            "screenName": "realDonaldTrump",
            "id": 25073877,
            "idStr": "25073877"
          }
        ],
        "hashtagEntities": [
          
        ],
        "mediaEntities": [
          
        ],
        "currentUserRetweetId": -1,
        "user": {
          "id": 50874573,
          "idStr": "50874573",
          "name": "vltxl 🇺🇸⭐⭐⭐🇺🇲",
          "screenName": "vltxl",
          "location": "",
          "description": "Founding Fathers had it right... Constitutionalist. #MAGA #KAG #TRUMP2020 #BuildTheWall #screwyouralgorithmtwittr",
          "descriptionURLEntities": [
            
          ],
          "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/1099162509477535744/yAd17wHv_normal.jpg",
          "url": null,
          "followersCount": 465,
          "status": null,
          "profileBackgroundColor": "C0DEED",
          "profileTextColor": "333333",
          "profileLinkColor": "1DA1F2",
          "profileSidebarFillColor": "DDEEF6",
          "profileSidebarBorderColor": "C0DEED",
          "profileUseBackgroundImage": true,
          "showAllInlineMedia": false,
          "friendsCount": 1063,
          "createdAt": 1245981647000,
          "favouritesCount": 15409,
          "utcOffset": -1,
          "timeZone": null,
          "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
          "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
          "profileBackgroundTiled": false,
          "lang": null,
          "statusesCount": 12543,
          "translator": false,
          "listedCount": 2,
          "geoEnabled": false,
          "contributorsEnabled": false,
          "originalProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1099162509477535744/yAd17wHv.jpg",
          "profileImageURL": "http://pbs.twimg.com/profile_images/1099162509477535744/yAd17wHv_normal.jpg",
          "biggerProfileImageURL": "http://pbs.twimg.com/profile_images/1099162509477535744/yAd17wHv_bigger.jpg",
          "miniProfileImageURL": "http://pbs.twimg.com/profile_images/1099162509477535744/yAd17wHv_mini.jpg",
          "originalProfileImageURL": "http://pbs.twimg.com/profile_images/1099162509477535744/yAd17wHv.jpg",
          "profileImageURLHttps": "https://pbs.twimg.com/profile_images/1099162509477535744/yAd17wHv_normal.jpg",
          "biggerProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1099162509477535744/yAd17wHv_bigger.jpg",
          "miniProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1099162509477535744/yAd17wHv_mini.jpg",
          "profileBackgroundImageURL": "http://abs.twimg.com/images/themes/theme1/bg.png",
          "profileBannerURL": "https://pbs.twimg.com/profile_banners/50874573/1550895634/web",
          "profileBannerRetinaURL": "https://pbs.twimg.com/profile_banners/50874573/1550895634/web_retina",
          "profileBannerIPadURL": "https://pbs.twimg.com/profile_banners/50874573/1550895634/ipad",
          "profileBannerIPadRetinaURL": "https://pbs.twimg.com/profile_banners/50874573/1550895634/ipad_retina",
          "profileBannerMobileURL": "https://pbs.twimg.com/profile_banners/50874573/1550895634/mobile",
          "profileBannerMobileRetinaURL": "https://pbs.twimg.com/profile_banners/50874573/1550895634/ipad_retina",
          "verified": false,
          "followRequestSent": false,
          "urlentity": {
            "start": 0,
            "end": 0,
            "url": "",
            "expandedURL": "",
            "displayURL": ""
          },
          "protected": false,
          "rateLimitStatus": null,
          "accessLevel": 0
        },
        "contributors": [
          
        ],
        "urlentities": [
          
        ],
        "favorited": false,
        "retweet": true,
        "retweetedByMe": false,
        "possiblySensitive": false,
        "truncated": false,
        "rateLimitStatus": null,
        "accessLevel": 0
      },
      {
        "createdAt": 1562901479000,
        "id": 1149518236997709825,
        "idStr": "1149518236997709825",
        "text": "From a buzzed Michelle Obama to a miraculous Paul Ryan: A man of straw needs a woman of gold. -  The Intoxicated Ipotane",
        "source": "<a href=\"https://cheapbotsdonequick.com\" rel=\"nofollow\">Cheap Bots, Done Quick!</a>",
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "inReplyToScreenName": null,
        "geoLocation": null,
        "place": null,
        "retweetCount": 0,
        "retweetedStatus": null,
        "userMentionEntities": [
          
        ],
        "hashtagEntities": [
          
        ],
        "mediaEntities": [
          
        ],
        "currentUserRetweetId": -1,
        "user": {
          "id": 835285190419300352,
          "idStr": "835285190419300352",
          "name": "a political mixology",
          "screenName": "iCommBot",
          "location": "Illinois, USA",
          "description": "i am a bot that experiments with the diffusion of intelligent semi-apolitical love. my guardian is kris weeks, a phd student at uiuc. please enjoy. smile.",
          "descriptionURLEntities": [
            
          ],
          "profileImageUrlHttps": "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
          "url": null,
          "followersCount": 2,
          "status": null,
          "profileBackgroundColor": "F5F8FA",
          "profileTextColor": "333333",
          "profileLinkColor": "1DA1F2",
          "profileSidebarFillColor": "DDEEF6",
          "profileSidebarBorderColor": "C0DEED",
          "profileUseBackgroundImage": true,
          "showAllInlineMedia": false,
          "friendsCount": 0,
          "createdAt": 1487982483000,
          "favouritesCount": 0,
          "utcOffset": -1,
          "timeZone": null,
          "profileBackgroundImageUrl": null,
          "profileBackgroundImageUrlHttps": null,
          "profileBackgroundTiled": false,
          "lang": null,
          "statusesCount": 20696,
          "translator": false,
          "listedCount": 1,
          "geoEnabled": false,
          "contributorsEnabled": false,
          "originalProfileImageURLHttps": "https://abs.twimg.com/sticky/default_profile_images/default_profile.png",
          "profileImageURL": "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
          "biggerProfileImageURL": "http://abs.twimg.com/sticky/default_profile_images/default_profile_bigger.png",
          "miniProfileImageURL": "http://abs.twimg.com/sticky/default_profile_images/default_profile_mini.png",
          "originalProfileImageURL": "http://abs.twimg.com/sticky/default_profile_images/default_profile.png",
          "profileImageURLHttps": "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
          "biggerProfileImageURLHttps": "https://abs.twimg.com/sticky/default_profile_images/default_profile_bigger.png",
          "miniProfileImageURLHttps": "https://abs.twimg.com/sticky/default_profile_images/default_profile_mini.png",
          "profileBackgroundImageURL": null,
          "profileBannerURL": null,
          "profileBannerRetinaURL": null,
          "profileBannerIPadURL": null,
          "profileBannerIPadRetinaURL": null,
          "profileBannerMobileURL": null,
          "profileBannerMobileRetinaURL": null,
          "verified": false,
          "followRequestSent": false,
          "urlentity": {
            "start": 0,
            "end": 0,
            "url": "",
            "expandedURL": "",
            "displayURL": ""
          },
          "protected": false,
          "rateLimitStatus": null,
          "accessLevel": 0
        },
        "contributors": [
          
        ],
        "urlentities": [
          
        ],
        "favorited": false,
        "retweet": false,
        "retweetedByMe": false,
        "possiblySensitive": false,
        "truncated": false,
        "rateLimitStatus": null,
        "accessLevel": 0
      },
      {
        "createdAt": 1562901478000,
        "id": 1149518232606298112,
        "idStr": "1149518232606298112",
        "text": "@Omagus Interesting that all the indignities far right conservatives were expecting to happen in the White House un… https://t.co/pcrIvI201i",
        "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
        "inReplyToStatusId": 1149517160080764930,
        "inReplyToUserId": 16280515,
        "inReplyToScreenName": "Omagus",
        "geoLocation": null,
        "place": null,
        "retweetCount": 0,
        "retweetedStatus": null,
        "userMentionEntities": [
          {
            "start": 0,
            "end": 7,
            "name": "Verbs McGillicuddy",
            "screenName": "Omagus",
            "id": 16280515,
            "idStr": "16280515"
          }
        ],
        "hashtagEntities": [
          
        ],
        "mediaEntities": [
          
        ],
        "currentUserRetweetId": -1,
        "user": {
          "id": 306263929,
          "idStr": "306263929",
          "name": "K",
          "screenName": "Damocleansword",
          "location": "",
          "description": "I reserve the right to change my mind.",
          "descriptionURLEntities": [
            
          ],
          "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/1142923353382182917/4tv8G0o-_normal.jpg",
          "url": null,
          "followersCount": 2156,
          "status": null,
          "profileBackgroundColor": "C6E2EE",
          "profileTextColor": "663B12",
          "profileLinkColor": "1F98C7",
          "profileSidebarFillColor": "DAECF4",
          "profileSidebarBorderColor": "C6E2EE",
          "profileUseBackgroundImage": true,
          "showAllInlineMedia": false,
          "friendsCount": 695,
          "createdAt": 1306510574000,
          "favouritesCount": 1463,
          "utcOffset": -1,
          "timeZone": null,
          "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme2/bg.gif",
          "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme2/bg.gif",
          "profileBackgroundTiled": false,
          "lang": null,
          "statusesCount": 116161,
          "translator": false,
          "listedCount": 48,
          "geoEnabled": true,
          "contributorsEnabled": false,
          "originalProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1142923353382182917/4tv8G0o-.jpg",
          "profileImageURL": "http://pbs.twimg.com/profile_images/1142923353382182917/4tv8G0o-_normal.jpg",
          "biggerProfileImageURL": "http://pbs.twimg.com/profile_images/1142923353382182917/4tv8G0o-_bigger.jpg",
          "miniProfileImageURL": "http://pbs.twimg.com/profile_images/1142923353382182917/4tv8G0o-_mini.jpg",
          "originalProfileImageURL": "http://pbs.twimg.com/profile_images/1142923353382182917/4tv8G0o-.jpg",
          "profileImageURLHttps": "https://pbs.twimg.com/profile_images/1142923353382182917/4tv8G0o-_normal.jpg",
          "biggerProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1142923353382182917/4tv8G0o-_bigger.jpg",
          "miniProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1142923353382182917/4tv8G0o-_mini.jpg",
          "profileBackgroundImageURL": "http://abs.twimg.com/images/themes/theme2/bg.gif",
          "profileBannerURL": "https://pbs.twimg.com/profile_banners/306263929/1484938187/web",
          "profileBannerRetinaURL": "https://pbs.twimg.com/profile_banners/306263929/1484938187/web_retina",
          "profileBannerIPadURL": "https://pbs.twimg.com/profile_banners/306263929/1484938187/ipad",
          "profileBannerIPadRetinaURL": "https://pbs.twimg.com/profile_banners/306263929/1484938187/ipad_retina",
          "profileBannerMobileURL": "https://pbs.twimg.com/profile_banners/306263929/1484938187/mobile",
          "profileBannerMobileRetinaURL": "https://pbs.twimg.com/profile_banners/306263929/1484938187/ipad_retina",
          "verified": false,
          "followRequestSent": false,
          "urlentity": {
            "start": 0,
            "end": 0,
            "url": "",
            "expandedURL": "",
            "displayURL": ""
          },
          "protected": false,
          "rateLimitStatus": null,
          "accessLevel": 0
        },
        "contributors": [
          
        ],
        "urlentities": [
          {
            "start": 117,
            "end": 140,
            "url": "https://t.co/pcrIvI201i",
            "expandedURL": "https://twitter.com/i/web/status/1149518232606298112",
            "displayURL": "twitter.com/i/web/status/1…"
          }
        ],
        "favorited": false,
        "retweet": false,
        "retweetedByMe": false,
        "possiblySensitive": false,
        "truncated": true,
        "rateLimitStatus": null,
        "accessLevel": 0
      },
      {
        "createdAt": 1562901478000,
        "id": 1149518232333635584,
        "idStr": "1149518232333635584",
        "text": "@kaspervol @ValentineShow Pres Obama is not a criminal. @realDonaldTrump is a conman who has gotten away with crime… https://t.co/jydEqAh73L",
        "source": "<a href=\"http://twitter.com/#!/download/ipad\" rel=\"nofollow\">Twitter for iPad</a>",
        "inReplyToStatusId": 1148641408800215040,
        "inReplyToUserId": 241581910,
        "inReplyToScreenName": "kaspervol",
        "geoLocation": null,
        "place": null,
        "retweetCount": 0,
        "retweetedStatus": null,
        "userMentionEntities": [
          {
            "start": 0,
            "end": 10,
            "name": "Tony Kasper",
            "screenName": "kaspervol",
            "id": 241581910,
            "idStr": "241581910"
          },
          {
            "start": 11,
            "end": 25,
            "name": "Phil Valentine",
            "screenName": "ValentineShow",
            "id": 54655169,
            "idStr": "54655169"
          },
          {
            "start": 56,
            "end": 72,
            "name": "Donald J. Trump",
            "screenName": "realDonaldTrump",
            "id": 25073877,
            "idStr": "25073877"
          }
        ],
        "hashtagEntities": [
          
        ],
        "mediaEntities": [
          
        ],
        "currentUserRetweetId": -1,
        "user": {
          "id": 1041094174127411200,
          "idStr": "1041094174127411200",
          "name": "AvA",
          "screenName": "AvAforBLUE",
          "location": "Earth ",
          "description": "Who is profiting from the chaos, and division of our nation ? Open your minds and hearts, and seek the truth. Our nation is in grave peril. We are one USA 🇺🇸",
          "descriptionURLEntities": [
            
          ],
          "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/1098326265076027396/ouDZiSpr_normal.jpg",
          "url": null,
          "followersCount": 3444,
          "status": null,
          "profileBackgroundColor": "F5F8FA",
          "profileTextColor": "333333",
          "profileLinkColor": "1DA1F2",
          "profileSidebarFillColor": "DDEEF6",
          "profileSidebarBorderColor": "C0DEED",
          "profileUseBackgroundImage": true,
          "showAllInlineMedia": false,
          "friendsCount": 3385,
          "createdAt": 1537051168000,
          "favouritesCount": 64024,
          "utcOffset": -1,
          "timeZone": null,
          "profileBackgroundImageUrl": null,
          "profileBackgroundImageUrlHttps": null,
          "profileBackgroundTiled": false,
          "lang": null,
          "statusesCount": 53836,
          "translator": false,
          "listedCount": 2,
          "geoEnabled": false,
          "contributorsEnabled": false,
          "originalProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1098326265076027396/ouDZiSpr.jpg",
          "profileImageURL": "http://pbs.twimg.com/profile_images/1098326265076027396/ouDZiSpr_normal.jpg",
          "biggerProfileImageURL": "http://pbs.twimg.com/profile_images/1098326265076027396/ouDZiSpr_bigger.jpg",
          "miniProfileImageURL": "http://pbs.twimg.com/profile_images/1098326265076027396/ouDZiSpr_mini.jpg",
          "originalProfileImageURL": "http://pbs.twimg.com/profile_images/1098326265076027396/ouDZiSpr.jpg",
          "profileImageURLHttps": "https://pbs.twimg.com/profile_images/1098326265076027396/ouDZiSpr_normal.jpg",
          "biggerProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1098326265076027396/ouDZiSpr_bigger.jpg",
          "miniProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1098326265076027396/ouDZiSpr_mini.jpg",
          "profileBackgroundImageURL": null,
          "profileBannerURL": "https://pbs.twimg.com/profile_banners/1041094174127411200/1553909414/web",
          "profileBannerRetinaURL": "https://pbs.twimg.com/profile_banners/1041094174127411200/1553909414/web_retina",
          "profileBannerIPadURL": "https://pbs.twimg.com/profile_banners/1041094174127411200/1553909414/ipad",
          "profileBannerIPadRetinaURL": "https://pbs.twimg.com/profile_banners/1041094174127411200/1553909414/ipad_retina",
          "profileBannerMobileURL": "https://pbs.twimg.com/profile_banners/1041094174127411200/1553909414/mobile",
          "profileBannerMobileRetinaURL": "https://pbs.twimg.com/profile_banners/1041094174127411200/1553909414/ipad_retina",
          "verified": false,
          "followRequestSent": false,
          "urlentity": {
            "start": 0,
            "end": 0,
            "url": "",
            "expandedURL": "",
            "displayURL": ""
          },
          "protected": false,
          "rateLimitStatus": null,
          "accessLevel": 0
        },
        "contributors": [
          
        ],
        "urlentities": [
          {
            "start": 117,
            "end": 140,
            "url": "https://t.co/jydEqAh73L",
            "expandedURL": "https://twitter.com/i/web/status/1149518232333635584",
            "displayURL": "twitter.com/i/web/status/1…"
          }
        ],
        "favorited": false,
        "retweet": false,
        "retweetedByMe": false,
        "possiblySensitive": false,
        "truncated": true,
        "rateLimitStatus": null,
        "accessLevel": 0
      },
      {
        "createdAt": 1562901477000,
        "id": 1149518230366482432,
        "idStr": "1149518230366482432",
        "text": "Chris Farrell: Obama State Dept. KNEW Hillary Clinton was Running Her Own Private Email Server! - Judicial Watch https://t.co/GZ14UwIsjV",
        "source": "<a href=\"http://twitter.com/#!/download/ipad\" rel=\"nofollow\">Twitter for iPad</a>",
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "inReplyToScreenName": null,
        "geoLocation": null,
        "place": null,
        "retweetCount": 0,
        "retweetedStatus": null,
        "userMentionEntities": [
          
        ],
        "hashtagEntities": [
          
        ],
        "mediaEntities": [
          
        ],
        "currentUserRetweetId": -1,
        "user": {
          "id": 770721915363205120,
          "idStr": "770721915363205120",
          "name": "Lamplighter Patriot ⭐️⭐️⭐️",
          "screenName": "SQbySnack",
          "location": "United States",
          "description": "Broken IDENTITY=Broken Life. WANDERING? Let's connect #Shepherd #Speaker #Coach #Grace #Righteous #Jesus #MAGA #Patriot #Tetelestai #WWG1WGA #Qanon #Q #RollTide",
          "descriptionURLEntities": [
            
          ],
          "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/1127050965251710978/KjGErjZa_normal.jpg",
          "url": null,
          "followersCount": 16773,
          "status": null,
          "profileBackgroundColor": "000000",
          "profileTextColor": "000000",
          "profileLinkColor": "981CEB",
          "profileSidebarFillColor": "000000",
          "profileSidebarBorderColor": "000000",
          "profileUseBackgroundImage": false,
          "showAllInlineMedia": false,
          "friendsCount": 16516,
          "createdAt": 1472589398000,
          "favouritesCount": 1552,
          "utcOffset": -1,
          "timeZone": null,
          "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
          "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
          "profileBackgroundTiled": false,
          "lang": null,
          "statusesCount": 18093,
          "translator": false,
          "listedCount": 73,
          "geoEnabled": false,
          "contributorsEnabled": false,
          "originalProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1127050965251710978/KjGErjZa.jpg",
          "profileImageURL": "http://pbs.twimg.com/profile_images/1127050965251710978/KjGErjZa_normal.jpg",
          "biggerProfileImageURL": "http://pbs.twimg.com/profile_images/1127050965251710978/KjGErjZa_bigger.jpg",
          "miniProfileImageURL": "http://pbs.twimg.com/profile_images/1127050965251710978/KjGErjZa_mini.jpg",
          "originalProfileImageURL": "http://pbs.twimg.com/profile_images/1127050965251710978/KjGErjZa.jpg",
          "profileImageURLHttps": "https://pbs.twimg.com/profile_images/1127050965251710978/KjGErjZa_normal.jpg",
          "biggerProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1127050965251710978/KjGErjZa_bigger.jpg",
          "miniProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1127050965251710978/KjGErjZa_mini.jpg",
          "profileBackgroundImageURL": "http://abs.twimg.com/images/themes/theme1/bg.png",
          "profileBannerURL": "https://pbs.twimg.com/profile_banners/770721915363205120/1545187969/web",
          "profileBannerRetinaURL": "https://pbs.twimg.com/profile_banners/770721915363205120/1545187969/web_retina",
          "profileBannerIPadURL": "https://pbs.twimg.com/profile_banners/770721915363205120/1545187969/ipad",
          "profileBannerIPadRetinaURL": "https://pbs.twimg.com/profile_banners/770721915363205120/1545187969/ipad_retina",
          "profileBannerMobileURL": "https://pbs.twimg.com/profile_banners/770721915363205120/1545187969/mobile",
          "profileBannerMobileRetinaURL": "https://pbs.twimg.com/profile_banners/770721915363205120/1545187969/ipad_retina",
          "verified": false,
          "followRequestSent": false,
          "urlentity": {
            "start": 0,
            "end": 0,
            "url": "",
            "expandedURL": "",
            "displayURL": ""
          },
          "protected": false,
          "rateLimitStatus": null,
          "accessLevel": 0
        },
        "contributors": [
          
        ],
        "urlentities": [
          {
            "start": 113,
            "end": 136,
            "url": "https://t.co/GZ14UwIsjV",
            "expandedURL": "https://www.judicialwatch.org/press-room/in-the-news/chris-farrell-obama-state-dept-knew-hillary-clinton-was-running-her-own-private-email-server/",
            "displayURL": "judicialwatch.org/press-room/in-…"
          }
        ],
        "favorited": false,
        "retweet": false,
        "retweetedByMe": false,
        "possiblySensitive": false,
        "truncated": false,
        "rateLimitStatus": null,
        "accessLevel": 0
      },
      {
        "createdAt": 1562901477000,
        "id": 1149518229695426565,
        "idStr": "1149518229695426565",
        "text": "RT @realDonaldTrump: Democrats had to quickly take down a tweet called “Kids In Cages, Inhumane Treatment at the Border,” because the horri…",
        "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "inReplyToScreenName": null,
        "geoLocation": null,
        "place": null,
        "retweetCount": 25909,
        "retweetedStatus": {
          "createdAt": 1562846926000,
          "id": 1149289425836367872,
          "idStr": "1149289425836367872",
          "text": "Democrats had to quickly take down a tweet called “Kids In Cages, Inhumane Treatment at the Border,” because the ho… https://t.co/xdiz18B25i",
          "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
          "inReplyToStatusId": -1,
          "inReplyToUserId": -1,
          "inReplyToScreenName": null,
          "geoLocation": null,
          "place": null,
          "retweetCount": 25909,
          "retweetedStatus": null,
          "userMentionEntities": [
            
          ],
          "hashtagEntities": [
            
          ],
          "mediaEntities": [
            
          ],
          "currentUserRetweetId": -1,
          "user": {
            "id": 25073877,
            "idStr": "25073877",
            "name": "Donald J. Trump",
            "screenName": "realDonaldTrump",
            "location": "Washington, DC",
            "description": "45th President of the United States of America🇺🇸",
            "descriptionURLEntities": [
              
            ],
            "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/874276197357596672/kUuht00m_normal.jpg",
            "url": "https://t.co/OMxB0x7xC5",
            "followersCount": 61853221,
            "status": null,
            "profileBackgroundColor": "6D5C18",
            "profileTextColor": "333333",
            "profileLinkColor": "1B95E0",
            "profileSidebarFillColor": "C5CEC0",
            "profileSidebarBorderColor": "BDDCAD",
            "profileUseBackgroundImage": true,
            "showAllInlineMedia": false,
            "friendsCount": 47,
            "createdAt": 1237383998000,
            "favouritesCount": 7,
            "utcOffset": -1,
            "timeZone": null,
            "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
            "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
            "profileBackgroundTiled": true,
            "lang": null,
            "statusesCount": 42819,
            "translator": false,
            "listedCount": 105155,
            "geoEnabled": true,
            "contributorsEnabled": false,
            "originalProfileImageURLHttps": "https://pbs.twimg.com/profile_images/874276197357596672/kUuht00m.jpg",
            "profileImageURL": "http://pbs.twimg.com/profile_images/874276197357596672/kUuht00m_normal.jpg",
            "biggerProfileImageURL": "http://pbs.twimg.com/profile_images/874276197357596672/kUuht00m_bigger.jpg",
            "miniProfileImageURL": "http://pbs.twimg.com/profile_images/874276197357596672/kUuht00m_mini.jpg",
            "originalProfileImageURL": "http://pbs.twimg.com/profile_images/874276197357596672/kUuht00m.jpg",
            "profileImageURLHttps": "https://pbs.twimg.com/profile_images/874276197357596672/kUuht00m_normal.jpg",
            "biggerProfileImageURLHttps": "https://pbs.twimg.com/profile_images/874276197357596672/kUuht00m_bigger.jpg",
            "miniProfileImageURLHttps": "https://pbs.twimg.com/profile_images/874276197357596672/kUuht00m_mini.jpg",
            "profileBackgroundImageURL": "http://abs.twimg.com/images/themes/theme1/bg.png",
            "profileBannerURL": "https://pbs.twimg.com/profile_banners/25073877/1560920145/web",
            "profileBannerRetinaURL": "https://pbs.twimg.com/profile_banners/25073877/1560920145/web_retina",
            "profileBannerIPadURL": "https://pbs.twimg.com/profile_banners/25073877/1560920145/ipad",
            "profileBannerIPadRetinaURL": "https://pbs.twimg.com/profile_banners/25073877/1560920145/ipad_retina",
            "profileBannerMobileURL": "https://pbs.twimg.com/profile_banners/25073877/1560920145/mobile",
            "profileBannerMobileRetinaURL": "https://pbs.twimg.com/profile_banners/25073877/1560920145/ipad_retina",
            "verified": true,
            "followRequestSent": false,
            "urlentity": {
              "start": 0,
              "end": 23,
              "url": "https://t.co/OMxB0x7xC5",
              "expandedURL": "http://www.Instagram.com/realDonaldTrump",
              "displayURL": "Instagram.com/realDonaldTrump"
            },
            "protected": false,
            "rateLimitStatus": null,
            "accessLevel": 0
          },
          "contributors": [
            
          ],
          "urlentities": [
            {
              "start": 117,
              "end": 140,
              "url": "https://t.co/xdiz18B25i",
              "expandedURL": "https://twitter.com/i/web/status/1149289425836367872",
              "displayURL": "twitter.com/i/web/status/1…"
            }
          ],
          "favorited": false,
          "retweet": false,
          "retweetedByMe": false,
          "possiblySensitive": false,
          "truncated": true,
          "rateLimitStatus": null,
          "accessLevel": 0
        },
        "userMentionEntities": [
          {
            "start": 3,
            "end": 19,
            "name": "Donald J. Trump",
            "screenName": "realDonaldTrump",
            "id": 25073877,
            "idStr": "25073877"
          }
        ],
        "hashtagEntities": [
          
        ],
        "mediaEntities": [
          
        ],
        "currentUserRetweetId": -1,
        "user": {
          "id": 788949232371851264,
          "idStr": "788949232371851264",
          "name": "Linda",
          "screenName": "LCG61790",
          "location": "New York, USA",
          "description": "Proud Strong American (NY 🙁) Woman, Wife, & Mother of 👫👬👧 God, Faith, Family, Country\n🇺🇸 #MAGA 🇺🇸 \nGod Bless America!! \n🎅I say Merry Christmas🤶",
          "descriptionURLEntities": [
            
          ],
          "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/835902334307749888/pmOGrjWt_normal.jpg",
          "url": null,
          "followersCount": 570,
          "status": null,
          "profileBackgroundColor": "F5F8FA",
          "profileTextColor": "333333",
          "profileLinkColor": "1DA1F2",
          "profileSidebarFillColor": "DDEEF6",
          "profileSidebarBorderColor": "C0DEED",
          "profileUseBackgroundImage": true,
          "showAllInlineMedia": false,
          "friendsCount": 415,
          "createdAt": 1476935130000,
          "favouritesCount": 41238,
          "utcOffset": -1,
          "timeZone": null,
          "profileBackgroundImageUrl": null,
          "profileBackgroundImageUrlHttps": null,
          "profileBackgroundTiled": false,
          "lang": null,
          "statusesCount": 38265,
          "translator": false,
          "listedCount": 3,
          "geoEnabled": false,
          "contributorsEnabled": false,
          "originalProfileImageURLHttps": "https://pbs.twimg.com/profile_images/835902334307749888/pmOGrjWt.jpg",
          "profileImageURL": "http://pbs.twimg.com/profile_images/835902334307749888/pmOGrjWt_normal.jpg",
          "biggerProfileImageURL": "http://pbs.twimg.com/profile_images/835902334307749888/pmOGrjWt_bigger.jpg",
          "miniProfileImageURL": "http://pbs.twimg.com/profile_images/835902334307749888/pmOGrjWt_mini.jpg",
          "originalProfileImageURL": "http://pbs.twimg.com/profile_images/835902334307749888/pmOGrjWt.jpg",
          "profileImageURLHttps": "https://pbs.twimg.com/profile_images/835902334307749888/pmOGrjWt_normal.jpg",
          "biggerProfileImageURLHttps": "https://pbs.twimg.com/profile_images/835902334307749888/pmOGrjWt_bigger.jpg",
          "miniProfileImageURLHttps": "https://pbs.twimg.com/profile_images/835902334307749888/pmOGrjWt_mini.jpg",
          "profileBackgroundImageURL": null,
          "profileBannerURL": "https://pbs.twimg.com/profile_banners/788949232371851264/1488129758/web",
          "profileBannerRetinaURL": "https://pbs.twimg.com/profile_banners/788949232371851264/1488129758/web_retina",
          "profileBannerIPadURL": "https://pbs.twimg.com/profile_banners/788949232371851264/1488129758/ipad",
          "profileBannerIPadRetinaURL": "https://pbs.twimg.com/profile_banners/788949232371851264/1488129758/ipad_retina",
          "profileBannerMobileURL": "https://pbs.twimg.com/profile_banners/788949232371851264/1488129758/mobile",
          "profileBannerMobileRetinaURL": "https://pbs.twimg.com/profile_banners/788949232371851264/1488129758/ipad_retina",
          "verified": false,
          "followRequestSent": false,
          "urlentity": {
            "start": 0,
            "end": 0,
            "url": "",
            "expandedURL": "",
            "displayURL": ""
          },
          "protected": false,
          "rateLimitStatus": null,
          "accessLevel": 0
        },
        "contributors": [
          
        ],
        "urlentities": [
          
        ],
        "favorited": false,
        "retweet": true,
        "retweetedByMe": false,
        "possiblySensitive": false,
        "truncated": false,
        "rateLimitStatus": null,
        "accessLevel": 0
      },
      {
        "createdAt": 1562901477000,
        "id": 1149518228810428416,
        "idStr": "1149518228810428416",
        "text": "RT @tonetalks: This is why #ados is the most necessary movement for black America since the era of Black Power. Obama created a entire issu…",
        "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "inReplyToScreenName": null,
        "geoLocation": null,
        "place": null,
        "retweetCount": 121,
        "retweetedStatus": {
          "createdAt": 1562704948000,
          "id": 1148693925265231872,
          "idStr": "1148693925265231872",
          "text": "This is why #ados is the most necessary movement for black America since the era of Black Power. Obama created a en… https://t.co/IM33baxgO9",
          "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
          "inReplyToStatusId": -1,
          "inReplyToUserId": -1,
          "inReplyToScreenName": null,
          "geoLocation": null,
          "place": null,
          "retweetCount": 121,
          "retweetedStatus": null,
          "userMentionEntities": [
            
          ],
          "hashtagEntities": [
            {
              "start": 12,
              "end": 17,
              "text": "ados"
            }
          ],
          "mediaEntities": [
            
          ],
          "currentUserRetweetId": -1,
          "user": {
            "id": 3820326674,
            "idStr": "3820326674",
            "name": "Antonio Moore",
            "screenName": "tonetalks",
            "location": "Los Angeles, CA",
            "description": "Antonio Moore graduated from UCLA & Loyola Law School. #ADOS 🇺🇸 is an Emmy nominated producer of Crack in the System aired on Al Jazeera.",
            "descriptionURLEntities": [
              
            ],
            "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/1128556401456865280/AVkDYSi7_normal.jpg",
            "url": "https://t.co/aiOmQQSWLG",
            "followersCount": 14406,
            "status": null,
            "profileBackgroundColor": "000000",
            "profileTextColor": "000000",
            "profileLinkColor": "ABB8C2",
            "profileSidebarFillColor": "000000",
            "profileSidebarBorderColor": "000000",
            "profileUseBackgroundImage": false,
            "showAllInlineMedia": false,
            "friendsCount": 706,
            "createdAt": 1444268861000,
            "favouritesCount": 4622,
            "utcOffset": -1,
            "timeZone": null,
            "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme14/bg.gif",
            "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme14/bg.gif",
            "profileBackgroundTiled": false,
            "lang": null,
            "statusesCount": 5599,
            "translator": false,
            "listedCount": 109,
            "geoEnabled": true,
            "contributorsEnabled": false,
            "originalProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1128556401456865280/AVkDYSi7.jpg",
            "profileImageURL": "http://pbs.twimg.com/profile_images/1128556401456865280/AVkDYSi7_normal.jpg",
            "biggerProfileImageURL": "http://pbs.twimg.com/profile_images/1128556401456865280/AVkDYSi7_bigger.jpg",
            "miniProfileImageURL": "http://pbs.twimg.com/profile_images/1128556401456865280/AVkDYSi7_mini.jpg",
            "originalProfileImageURL": "http://pbs.twimg.com/profile_images/1128556401456865280/AVkDYSi7.jpg",
            "profileImageURLHttps": "https://pbs.twimg.com/profile_images/1128556401456865280/AVkDYSi7_normal.jpg",
            "biggerProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1128556401456865280/AVkDYSi7_bigger.jpg",
            "miniProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1128556401456865280/AVkDYSi7_mini.jpg",
            "profileBackgroundImageURL": "http://abs.twimg.com/images/themes/theme14/bg.gif",
            "profileBannerURL": "https://pbs.twimg.com/profile_banners/3820326674/1455840815/web",
            "profileBannerRetinaURL": "https://pbs.twimg.com/profile_banners/3820326674/1455840815/web_retina",
            "profileBannerIPadURL": "https://pbs.twimg.com/profile_banners/3820326674/1455840815/ipad",
            "profileBannerIPadRetinaURL": "https://pbs.twimg.com/profile_banners/3820326674/1455840815/ipad_retina",
            "profileBannerMobileURL": "https://pbs.twimg.com/profile_banners/3820326674/1455840815/mobile",
            "profileBannerMobileRetinaURL": "https://pbs.twimg.com/profile_banners/3820326674/1455840815/ipad_retina",
            "verified": false,
            "followRequestSent": false,
            "urlentity": {
              "start": 0,
              "end": 23,
              "url": "https://t.co/aiOmQQSWLG",
              "expandedURL": "http://www.tonetalks.org",
              "displayURL": "tonetalks.org"
            },
            "protected": false,
            "rateLimitStatus": null,
            "accessLevel": 0
          },
          "contributors": [
            
          ],
          "urlentities": [
            {
              "start": 117,
              "end": 140,
              "url": "https://t.co/IM33baxgO9",
              "expandedURL": "https://twitter.com/i/web/status/1148693925265231872",
              "displayURL": "twitter.com/i/web/status/1…"
            }
          ],
          "favorited": false,
          "retweet": false,
          "retweetedByMe": false,
          "possiblySensitive": false,
          "truncated": true,
          "rateLimitStatus": null,
          "accessLevel": 0
        },
        "userMentionEntities": [
          {
            "start": 3,
            "end": 13,
            "name": "Antonio Moore",
            "screenName": "tonetalks",
            "id": 3820326674,
            "idStr": "3820326674"
          }
        ],
        "hashtagEntities": [
          {
            "start": 27,
            "end": 32,
            "text": "ados"
          }
        ],
        "mediaEntities": [
          
        ],
        "currentUserRetweetId": -1,
        "user": {
          "id": 24048665,
          "idStr": "24048665",
          "name": "Mr. Langston Burgundy from Reigal view",
          "screenName": "Tdubble",
          "location": "Honolulu Hawaii",
          "description": "FBA🇺🇸",
          "descriptionURLEntities": [
            
          ],
          "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/1021090835130081282/BBUBdUBX_normal.jpg",
          "url": "https://t.co/47eyg9VVBw",
          "followersCount": 3488,
          "status": null,
          "profileBackgroundColor": "494D4D",
          "profileTextColor": "03050F",
          "profileLinkColor": "0084B4",
          "profileSidebarFillColor": "43444D",
          "profileSidebarBorderColor": "000000",
          "profileUseBackgroundImage": true,
          "showAllInlineMedia": false,
          "friendsCount": 773,
          "createdAt": 1236895179000,
          "favouritesCount": 3092,
          "utcOffset": -1,
          "timeZone": null,
          "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
          "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
          "profileBackgroundTiled": true,
          "lang": null,
          "statusesCount": 48108,
          "translator": false,
          "listedCount": 16,
          "geoEnabled": true,
          "contributorsEnabled": false,
          "originalProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1021090835130081282/BBUBdUBX.jpg",
          "profileImageURL": "http://pbs.twimg.com/profile_images/1021090835130081282/BBUBdUBX_normal.jpg",
          "biggerProfileImageURL": "http://pbs.twimg.com/profile_images/1021090835130081282/BBUBdUBX_bigger.jpg",
          "miniProfileImageURL": "http://pbs.twimg.com/profile_images/1021090835130081282/BBUBdUBX_mini.jpg",
          "originalProfileImageURL": "http://pbs.twimg.com/profile_images/1021090835130081282/BBUBdUBX.jpg",
          "profileImageURLHttps": "https://pbs.twimg.com/profile_images/1021090835130081282/BBUBdUBX_normal.jpg",
          "biggerProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1021090835130081282/BBUBdUBX_bigger.jpg",
          "miniProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1021090835130081282/BBUBdUBX_mini.jpg",
          "profileBackgroundImageURL": "http://abs.twimg.com/images/themes/theme1/bg.png",
          "profileBannerURL": "https://pbs.twimg.com/profile_banners/24048665/1459405834/web",
          "profileBannerRetinaURL": "https://pbs.twimg.com/profile_banners/24048665/1459405834/web_retina",
          "profileBannerIPadURL": "https://pbs.twimg.com/profile_banners/24048665/1459405834/ipad",
          "profileBannerIPadRetinaURL": "https://pbs.twimg.com/profile_banners/24048665/1459405834/ipad_retina",
          "profileBannerMobileURL": "https://pbs.twimg.com/profile_banners/24048665/1459405834/mobile",
          "profileBannerMobileRetinaURL": "https://pbs.twimg.com/profile_banners/24048665/1459405834/ipad_retina",
          "verified": false,
          "followRequestSent": false,
          "urlentity": {
            "start": 0,
            "end": 23,
            "url": "https://t.co/47eyg9VVBw",
            "expandedURL": "http://m.youtube.com/#/user/Tdubble?&desktop_uri=%2Fuser%2FTdubble",
            "displayURL": "m.youtube.com/#/user/Tdubble…"
          },
          "protected": false,
          "rateLimitStatus": null,
          "accessLevel": 0
        },
        "contributors": [
          
        ],
        "urlentities": [
          
        ],
        "favorited": false,
        "retweet": true,
        "retweetedByMe": false,
        "possiblySensitive": false,
        "truncated": false,
        "rateLimitStatus": null,
        "accessLevel": 0
      },
      {
        "createdAt": 1562901476000,
        "id": 1149518223827595266,
        "idStr": "1149518223827595266",
        "text": "RT @DELAROSA116: HOPINGTHIS GETS TO U,CHIEF&THOSE AT THE DRAWING BOARD CONCERNING THESE ISSUES,THIS IS ABOUT AS OPEN A LETTER I CAN WRITE K…",
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "inReplyToScreenName": null,
        "geoLocation": null,
        "place": null,
        "retweetCount": 1,
        "retweetedStatus": {
          "createdAt": 1562901460000,
          "id": 1149518159533056001,
          "idStr": "1149518159533056001",
          "text": "HOPINGTHIS GETS TO U,CHIEF&THOSE AT THE DRAWING BOARD CONCERNING THESE ISSUES,THIS IS ABOUT AS OPEN A LETTER I CAN… https://t.co/Tx7mHdix2N",
          "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
          "inReplyToStatusId": -1,
          "inReplyToUserId": -1,
          "inReplyToScreenName": null,
          "geoLocation": null,
          "place": null,
          "retweetCount": 1,
          "retweetedStatus": null,
          "userMentionEntities": [
            
          ],
          "hashtagEntities": [
            
          ],
          "mediaEntities": [
            
          ],
          "currentUserRetweetId": -1,
          "user": {
            "id": 1060337813932138496,
            "idStr": "1060337813932138496",
            "name": "DELAROSA1",
            "screenName": "DELAROSA116",
            "location": "",
            "description": "I love America, I love God. I will fight to the end, for God's world. Americana,ALL the way, not opening bank accounts,nor looking for love,but thanks anyway.",
            "descriptionURLEntities": [
              
            ],
            "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td_normal.jpg",
            "url": null,
            "followersCount": 1741,
            "status": null,
            "profileBackgroundColor": "F5F8FA",
            "profileTextColor": "333333",
            "profileLinkColor": "1DA1F2",
            "profileSidebarFillColor": "DDEEF6",
            "profileSidebarBorderColor": "C0DEED",
            "profileUseBackgroundImage": true,
            "showAllInlineMedia": false,
            "friendsCount": 3003,
            "createdAt": 1541639209000,
            "favouritesCount": 4557,
            "utcOffset": -1,
            "timeZone": null,
            "profileBackgroundImageUrl": null,
            "profileBackgroundImageUrlHttps": null,
            "profileBackgroundTiled": false,
            "lang": null,
            "statusesCount": 11162,
            "translator": false,
            "listedCount": 2,
            "geoEnabled": false,
            "contributorsEnabled": false,
            "originalProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td.jpg",
            "profileImageURL": "http://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td_normal.jpg",
            "biggerProfileImageURL": "http://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td_bigger.jpg",
            "miniProfileImageURL": "http://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td_mini.jpg",
            "originalProfileImageURL": "http://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td.jpg",
            "profileImageURLHttps": "https://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td_normal.jpg",
            "biggerProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td_bigger.jpg",
            "miniProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td_mini.jpg",
            "profileBackgroundImageURL": null,
            "profileBannerURL": "https://pbs.twimg.com/profile_banners/1060337813932138496/1548196415/web",
            "profileBannerRetinaURL": "https://pbs.twimg.com/profile_banners/1060337813932138496/1548196415/web_retina",
            "profileBannerIPadURL": "https://pbs.twimg.com/profile_banners/1060337813932138496/1548196415/ipad",
            "profileBannerIPadRetinaURL": "https://pbs.twimg.com/profile_banners/1060337813932138496/1548196415/ipad_retina",
            "profileBannerMobileURL": "https://pbs.twimg.com/profile_banners/1060337813932138496/1548196415/mobile",
            "profileBannerMobileRetinaURL": "https://pbs.twimg.com/profile_banners/1060337813932138496/1548196415/ipad_retina",
            "verified": false,
            "followRequestSent": false,
            "urlentity": {
              "start": 0,
              "end": 0,
              "url": "",
              "expandedURL": "",
              "displayURL": ""
            },
            "protected": false,
            "rateLimitStatus": null,
            "accessLevel": 0
          },
          "contributors": [
            
          ],
          "urlentities": [
            {
              "start": 116,
              "end": 139,
              "url": "https://t.co/Tx7mHdix2N",
              "expandedURL": "https://twitter.com/i/web/status/1149518159533056001",
              "displayURL": "twitter.com/i/web/status/1…"
            }
          ],
          "favorited": false,
          "retweet": false,
          "retweetedByMe": false,
          "possiblySensitive": false,
          "truncated": true,
          "rateLimitStatus": null,
          "accessLevel": 0
        },
        "userMentionEntities": [
          {
            "start": 3,
            "end": 15,
            "name": "DELAROSA1",
            "screenName": "DELAROSA116",
            "id": 1060337813932138496,
            "idStr": "1060337813932138496"
          }
        ],
        "hashtagEntities": [
          
        ],
        "mediaEntities": [
          
        ],
        "currentUserRetweetId": -1,
        "user": {
          "id": 1060337813932138496,
          "idStr": "1060337813932138496",
          "name": "DELAROSA1",
          "screenName": "DELAROSA116",
          "location": "",
          "description": "I love America, I love God. I will fight to the end, for God's world. Americana,ALL the way, not opening bank accounts,nor looking for love,but thanks anyway.",
          "descriptionURLEntities": [
            
          ],
          "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td_normal.jpg",
          "url": null,
          "followersCount": 1741,
          "status": null,
          "profileBackgroundColor": "F5F8FA",
          "profileTextColor": "333333",
          "profileLinkColor": "1DA1F2",
          "profileSidebarFillColor": "DDEEF6",
          "profileSidebarBorderColor": "C0DEED",
          "profileUseBackgroundImage": true,
          "showAllInlineMedia": false,
          "friendsCount": 3003,
          "createdAt": 1541639209000,
          "favouritesCount": 4557,
          "utcOffset": -1,
          "timeZone": null,
          "profileBackgroundImageUrl": null,
          "profileBackgroundImageUrlHttps": null,
          "profileBackgroundTiled": false,
          "lang": null,
          "statusesCount": 11162,
          "translator": false,
          "listedCount": 2,
          "geoEnabled": false,
          "contributorsEnabled": false,
          "originalProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td.jpg",
          "profileImageURL": "http://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td_normal.jpg",
          "biggerProfileImageURL": "http://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td_bigger.jpg",
          "miniProfileImageURL": "http://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td_mini.jpg",
          "originalProfileImageURL": "http://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td.jpg",
          "profileImageURLHttps": "https://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td_normal.jpg",
          "biggerProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td_bigger.jpg",
          "miniProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1102076522687619072/33ZUR8td_mini.jpg",
          "profileBackgroundImageURL": null,
          "profileBannerURL": "https://pbs.twimg.com/profile_banners/1060337813932138496/1548196415/web",
          "profileBannerRetinaURL": "https://pbs.twimg.com/profile_banners/1060337813932138496/1548196415/web_retina",
          "profileBannerIPadURL": "https://pbs.twimg.com/profile_banners/1060337813932138496/1548196415/ipad",
          "profileBannerIPadRetinaURL": "https://pbs.twimg.com/profile_banners/1060337813932138496/1548196415/ipad_retina",
          "profileBannerMobileURL": "https://pbs.twimg.com/profile_banners/1060337813932138496/1548196415/mobile",
          "profileBannerMobileRetinaURL": "https://pbs.twimg.com/profile_banners/1060337813932138496/1548196415/ipad_retina",
          "verified": false,
          "followRequestSent": false,
          "urlentity": {
            "start": 0,
            "end": 0,
            "url": "",
            "expandedURL": "",
            "displayURL": ""
          },
          "protected": false,
          "rateLimitStatus": null,
          "accessLevel": 0
        },
        "contributors": [
          
        ],
        "urlentities": [
          
        ],
        "favorited": false,
        "retweet": true,
        "retweetedByMe": false,
        "possiblySensitive": false,
        "truncated": false,
        "rateLimitStatus": null,
        "accessLevel": 0
      }
    ],
    "refreshURL": "?since_id=1149518237870071808&q=obama&include_entities=1",
    "rateLimitStatus": {
      "remaining": 176,
      "limit": 180,
      "resetTimeInSeconds": 1562901967,
      "secondsUntilReset": 469,
      "remainingHits": 176
    },
    "accessLevel": 1
  }